/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_vehicle_router_NativeLibraryRunner */

#ifndef _Included_com_vehicle_router_NativeLibraryRunner
#define _Included_com_vehicle_router_NativeLibraryRunner
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_vehicle_router_NativeLibraryRunner
 * Method:    helloNative
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_vehicle_router_NativeLibraryRunner_helloNative(JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
